# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 00:07
from __future__ import unicode_literals

from django.db import migrations
import csv


def datarater(apps,schema_editor):
    Rater = apps.get_model('app','Rater')
    with open('/Users/chucklapress/tiy-projects/movieReview_new/u.user', 'r') as infile:
        data = csv.reader(infile, delimiter='|')
        for row in data:
            Rater.objects.create(id=row[0], age=row[1], gender=row[2], occupation=row[3], zipcode=row[4])




class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
    migrations.RunPython(datarater),

    ]
