# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 21:35
from __future__ import unicode_literals

from django.db import migrations
import csv

def datamovie(apps,schema_editor):
    Movie = apps.get_model('app','Movie')
    with open('/Users/chucklapress/tiy-projects/movieReview_new/movie_review_new/u.item',encoding='latin1') as inFile:
        data = csv.reader(inFile, delimiter='|')
        for row in data:
            Movie.objects.create(
            id=row[0], movie_title=row[1], release_date=row[2], video_release_date=row[3], IMBd_URL=row[4], unknown=row[5], action=row[6], adventure=row[7], animation=row[8], childrens=row[9], comedy=row[10], crime=row[11],
            documentary=row[12], drama=row[13], fantasy=row[14], film_noir=row[15], horror=row[16], musical=row[17], mystery=row[18], romance=row[19], sci_fi=row[20], thriller=row[21], war=row[22], western=row[23])



class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160723_2133'),
    ]

    operations = [
    migrations.RunPython(datamovie),
    ]
