# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 21:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20160723_2138'),
    ]

    operations = [
    
    ]
