# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-24 19:08
from __future__ import unicode_literals

from django.db import migrations
from django.db.models import Avg, Count



def top_twenty(apps, schema_editor):
    Movie = apps.get_model('app', 'Movie')
    Review = apps.get_model('app', 'Review')
    Average = apps.get_model('app', 'Average')

    movies = Movie.objects.all()
    for movie in movies:
        average_dict = Review.objects.filter(movie=movie.id).values('rating').aggregate(average=Avg('rating'))
        average = average_dict.get('average')
        print(movie.movie_title, average)
        total_dict = Review.objects.filter(movie=movie.id).values('rating').aggregate(number_rating=Count('rating'))
        total = total_dict.get('number_rating')
        print(total)
        if average != None:
            Average.objects.create(
                movie=movie,
                average=average,
                number_ratings=total
                )

    



class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20160723_2157'),
    ]

    operations = [
    migrations.RunPython(top_twenty),
    ]
